### ISSUE TITLE
Hi, can you explain how to authenticate?

### ISSUE THREAD

**Issue by holtzermann17** [iensu/org-github-issues#12]
I get a message like:

`error in process filter: url-http-handle-authentication: Wrong authorization used for https://api.github.com/repos/holtzermann17/toki-pona-emoji/issues`

I'm not sure what I need to do to get the authentication set up correctly. Could you please add some extra information about that?

**Comment by iensu** [comment]
Hi! Thanks for reporting this! 

I run into the same issue when trying to sync. It has to do with how the underlying github client package is handling authenticated requests, so will have to do some digging. @iocanel are you also seeing the issue?

**Comment by iocanel** [comment]
> Hi! Thanks for reporting this!
> 
> I run into the same issue when trying to sync. It has to do with how the underlying github client package is handling authenticated requests, so will have to do some digging. @iocanel are you also seeing the issue?

No, I don't see this issue. Maybe, its something introduced in latest version of `gh` or `ghub`. Here's what I use:

     ("gh.el" . "f029fc11f345ef04ab62ee91c38657e29c462fea")
     ("ghub" . "ca6b115c46d8ab12ae76037d4dadfc92a62a9904")

**Comment by iensu** [comment]
@iocanel I can't find any suspicious commits since the hashes you shared there... I wonder why it ever worked hehe. 

@holtzermann17 I was able to authenticate by passing a personal access token explicitly. This requires some changes to the code, but I'll try and have a fix out in a couple of days. Sorry about the delay, but I'm quite swamped with work atm. :)

**Comment by iensu** [comment]
@holtzermann17 are you able to try this PR out and see if it works for you? The README should provide all the information you need, but if not please tell me and I'll update it. 

https://github.com/iensu/org-github-issues/pull/13
